### ISSUE TITLE
about expression encoder

### ISSUE THREAD

**Issue by LangR7** [radekd91/emoca#14]
Hello, great job. Emoca have a dedicated expression encoder. I want to know where I can find the structure of this encoder? I don't seem to find it in the paper and supplementary materials. Thank you for your answers

**Comment by radekd91** [comment]
Hello. We use exactly the same architecture for the expression encoder as DECA uses. In fact we clone the DECA encoder and then further finetune it. It's basically a standard issue resnet. You can find the details of the architecture here: 
https://github.com/radekd91/emoca/blob/release/EMOCA/gdl/models/DecaEncoder.py#L62

**Comment by LangR7** [comment]
thanks for your answer！
