### ISSUE TITLE
How do I use the generated 3D mesh to render a target face with expressions from source actor?

### ISSUE THREAD

**Issue by Suvi-dha** [radekd91/emoca#15]
Once the 3D mesh is generated of the source actor, can we use it to modify the expressions of the target actor?

**Comment by radekd91** [comment]
Yes! When running the demos, use the save `--save_codes` option (for both of your actors' images/videos). In the codes you will find everything that EMOCA predicted - shape vector, expression vector, jaw rotation and others. Just take the expression and the jaw of the source actor and replace them with the ones of the target vector. After that you need to take this mixture of parameters and run an EMOCA decode step. The resulting mesh will be what you're looking for.

**Comment by Suvi-dha** [comment]
Thanks a lot! I will give a try :)

**Comment by Suvi-dha** [comment]
Hi, sorry for troubling you again, but would you please point me to EMOCA decode file in the code base?

**Comment by Suvi-dha** [comment]
I could find the decode code. Thanks. Closing the issue.

**Comment by radekd91** [comment]
Thanks! Sorry I missed your last question so I didn't reply.

If you do end up coding up a retargeting example, a PR is always welcome.
:-)

**Comment by Suvi-dha** [comment]
I will do that asap. Thanks!

**Comment by emlcpfx** [comment]
Hi @Suvi-dha , I’d love to talk to you about your work with EMOCA - eric@cleanplatefx.com.

**Comment by Suvi-dha** [comment]
@emlcpfx Sure. I have responded on your email. Thanks!

**Comment by theohsiung** [comment]
Hi @Suvi-dha I'm also interested in transfering the expreession into another source face could you show me how you did it?
- theobear870924@gmail.com
