### ISSUE TITLE
how to use generating code(.npy) to generate img(geometry_detail.png)

### ISSUE THREAD

**Issue by LangR7** [radekd91/emoca#23]
Hello, I would like to know how to restore the corresponding .png and .obj (such as geometry_detail.png, mesh_coarse_detail.obj, etc.) from the generated .npy (such as exp.npy, etc.) files
thanks for your help

**Comment by revantteotia** [comment]
hey @LangR7, did you figure it out? 
how did you generate .png and .obj from the generated .npy codes?
