### ISSUE TITLE
Are the jaw vector and root vector same as in DECA?

### ISSUE THREAD

**Issue by ujjawalcse** [radekd91/emoca#25]
Hey @radekd91 ,
Thank you so much for this amazing work.

I tried the demo code and saved the exp,pose and shape codes.
I have some questions regarding the same.

Since pose is 6-d vector , I'm interpreting first 3 elements as root axis-angle rotation and last 3 elements
as jaw axis angle representation. Am i interpreting correctly?

Are the exp (containing 50 elements) corresponds to the Flame first 50 expressions parameters? 
Are the shape (containing 100 elements) corresponds to the Flame first 100 shape parameters?

**Comment by radekd91** [comment]
Hey @ujjawalcse . Exactly as you say, EMOCA predicts the same spaces as DECA. Also to be more precise, the shape, global rotation and jaw rotation and the camera are taken from official DECA. What EMOCA predicts on top is just the expression vector.

**Comment by ujjawalcse** [comment]
Got it. Thanks.
