### ISSUE TITLE
error in video reconstruction

### ISSUE THREAD

**Issue by Gentergt** [radekd91/emoca#26]
Hi, when I do the video reconstruction and run the test_emoca_on_video.py script, there is an error "ffmpeg._run.Error: ffprobe error (see stderr output for detail)", do anyone know how to fix it? Thx.

**Comment by radekd91** [comment]
Can be one of two things:

1) your ffmpeg might be broken
2) the video is not ffmpeg readable.

Could be either but I think the ffmpeg actually comes with the python
ffmpeg package and should be working. 2) is more likely.

**Comment by XD666** [comment]
I encountered the same issue. No idea to fix this. The ffmpeg version is 4.4.2 from pycharm interpreter
For 2), I  tried the default video (2-25-854x480_affwild2.mp4) and others, but errors occurred too.

**Comment by Gentergt** [comment]
Thx,  I tried the default video and encounter this issue now, so maybe the ffmpeg is broken, I need to check it.

**Comment by RainEggplant** [comment]
Try running `conda install libiconv`. @Gentergt @XD666

**Comment by Gentergt** [comment]
It solves this issue, but raises another one: ffmpeg: symbol lookup error: /home/c00679255/anaconda3/envs/work36_cu11/bin/../lib/./libgnutls.so.30: undefined symbol: mpn_copyi, version HOGWEED_6
