### ISSUE TITLE
RuntimeError: Not compiled with GPU support

### ISSUE THREAD

**Issue by XD666** [radekd91/emoca#27]
Anyone encounters this issue when running test_emoca_on_video.py?

/work36_cu11/lib/python3.6/site-packages/pytorch3d/renderer/mesh/rasterize_meshes.py", line 320, in forward
    cull_backfaces,
RuntimeError: Not compiled with GPU support

I searched it looks like the pytorch3d issue but I have pytorch3D 0.6 installed.

**Comment by radekd91** [comment]
Your pytorch or pytorch3d is not compiled with GPU support. Compile it with
GPU support or install the version that has it. Of course you also need a
compatible GPU for that

**Comment by XD666** [comment]
Hi @radekd91 thanks for your comment! I installed PyTorch with GPU version (1.91) which is verified by running the following
torch.cuda.is_available()) == True

As for pytoch3d, how can I check if GPU version? I re-run the installation by 
pip install git+https://github.com/facebookresearch/pytorch3d.git@v0.6.0

And I can see the pytorch3d version is 0.6.  

FYR: my GPU is 3090, and Driver Version: 515.65.01    CUDA Version: 11.7 

It still happens the issue any other suggestion/solution?

**Comment by XD666** [comment]
Solved by re-install CUDA and ADD CUDA_HOME path to bashrc.

Then pip uninstall pytorch3d
and re-install by
pip install git+https://github.com/facebookresearch/pytorch3d.git@v0.6.0
