### ISSUE TITLE
Question on val/test split of AffectNet

### ISSUE THREAD

**Issue by eehuangzhangjin** [radekd91/emoca#45]
Thanks for contributing such great work!!!

I am interested in EMOCA, and I want to reproduce the training of EMOCA. 
However, I can NOT access the two files for splitting the validation/test set of AffectNet, as in https://github.com/radekd91/emoca/blob/fef5472a2fe3c47d8c5ffa56ad13928a790df1ab/gdl/datasets/AffectNetDataModule.py#L1519 and
https://github.com/radekd91/emoca/blob/fef5472a2fe3c47d8c5ffa56ad13928a790df1ab/gdl/datasets/AffectNetDataModule.py#L1521

Would you please provide me with these two files?
Thanks.

**Comment by Cryst4L9527** [comment]
@eehuangzhangjin I've got the same question, have you solved it? How did you get the pkl?
