### ISSUE TITLE
How to get 256x256 frames in test_emoca_on_video.py instead of 224x224?

### ISSUE THREAD

**Issue by leg0m4n** [radekd91/emoca#50]
Hi there!

Thank you so much for your work, it's remarkable!

When I process the video using your test_emoca_on_video.py, I get frames of shape 224x224, I was wondering if there is any chance to get a larger area, let's say 256x256?

On a different note, can your model work on high res videos - let's say 1024x1024 talking face video(like celeb-hq)?

My all best,
Richard

**Comment by radekd91** [comment]
The whole architecture is set up to use 224x224. If you need a different resolution, I suggest you pre/postprocess the input/output images. That is of course, unless you want to train your own EMOCA that operates on 256x256 or any otehr resolution
