### ISSUE TITLE
Excessive upper face movements in EMOCA v1

### ISSUE THREAD

**Issue by khalidhnv** [radekd91/emoca#51]
First of all thank you very much for your work. 

During conversion of 2D video using EMOCA v1 I noticed there's excessive upper face movements introduced by EMOCA. For example, upper head, eye brows and nose keep moving although original video doesn't have such movements (mainly keeps head straight and talks). So I was wondering if you're aware of it and if you have any recommendation for solving such issue.

Thanks in advance!

**Comment by radekd91** [comment]
It is true. EMOCA is a single image method and this becomes apparent in
some videos. EMOCA 2.0 should do a much better job in those regards so I
recommend using that one.

**Comment by khalidhnv** [comment]
thanks for quick response, i'll test it out then!
