### ISSUE TITLE
Outputting Detailed Rendering in higher resolution

### ISSUE THREAD

**Issue by leg0m4n** [radekd91/emoca#62]
Hi there!

I'm wondering if there is any way to make deca.decode produce renders of quality 512x512 instead of 224x224 when I feed it all the FLAME parameters(exp, pose, shape, etc.)? 

If not and it's all model-dependent, I assume the only other option I have is to train EMOCA on a higher-resolution dataset(for example CelebV-HQ). What modules should I change then and how would it generally change the training procedure?

My all best,
Rich

**Comment by emlcpfx** [comment]
It is possible. We're rendering our UV Pass at 896x896. Look in the cfg.yaml in the image_size parameter (emoca\assets\EMOCA\models\EMOCA_v2_lr_mse_20\cfg.yaml). Try messing around with that. It's on around line 290.

Check out our YouTube video about our R&D: https://youtu.be/uSxgt5mcbXM?si=P_XTFCA2nN9GprOs

**Comment by leg0m4n** [comment]
Hey @emlcpfx ! Thanks so much for the tip!
Really cool what you are doing with face enhancement! I am myself using it for Memory Face model, which is currently SOTA on the LipSync task. Seems like EMOCA/DECA is now a go-to solution for the parametric head model.
