### ISSUE TITLE
resize mesh

### ISSUE THREAD

**Issue by ImistroI** [radekd91/emoca#76]
Hello,
is it possible to change the size of the mesh when generating the meshes from the video?
Because currently the meshes are very small and want them in a bigger size.

Thanks in advance.

**Comment by radekd91** [comment]
There is no option like this but it's very easy to do that yourself. Just
multiply the vertex tensor with whatever sizing factor you want and save
the meshes after.

**Comment by ImistroI** [comment]
Thank u very much for ur answer. the reason for the question was that I want to adding eyeball meshes in the position for the eyes. I am using the script from the [FFHQ-UV repo](https://github.com/csbhr/FFHQ-UV/blob/main/Mesh_Add_EyeBall/run_mesh_add_eyeball.py). Running the script with the EMOCA meshes as input throws me an error. The error is: 
```
File "./FFHQ-UV/Mesh_Add_EyeBall/run_mesh_add_eyeball.py", line 319, in start_add_mesh
    L_ball_mesh, R_ball_mesh = add_eye_ball(head_mesh['v'], L_ball_mesh, R_ball_mesh)
  File "./FFHQ-UV/Mesh_Add_EyeBall/run_mesh_add_eyeball.py", line 286, in add_eye_ball
    _, L_ball_mesh['v'] = fit_icp_scale_RT(L_ball_mesh['v'][eye_ball_vtx_idxL], head_vtx[eye_bag_vtx_idxL],
IndexError: index 8536 is out of bounds for axis 0 with size 5023
```
The reason for the error is vertices (v in the file) in the EMOCA meshes are capped to 5023 lines while the intended FLAME meshes from the FFHQ-UV repo has ~10000 vertices.Is there a way to increase the amount of vertices in the EMOCA meshes but still maintain the FLAME topology? 

Thanks in advance :)

**Comment by radekd91** [comment]
The FLAME mesh topology which is what we already has eyeballs.

If you want to map FLAME topology on some other topology, that is not a
trivial operation but something that would involve some iterative
optimization to solve the alignment problem and this is not something we
provide here.
