### ISSUE TITLE
Does the 'Expression Encoder' fineturned in Detail Stage?

### ISSUE THREAD

**Issue by kjhgfdsaas** [radekd91/emoca#8]
Dear Radek Daněček

Good morning, I have a question about the pipeline. I read DECA and EMOCA, but confused on the EMOCA Detail Stage. The psi comes from 'Expression Encoder' in EMOCA different as in DECA. So can you please tell me does the 'Expression Encoder' fineturned in deatil stage in EMOCA?

**Comment by radekd91** [comment]
Neither DECA nor EMOCA trainings do not finetune any part of the coarse stage when training the detail stage. The difference between DECA and EMOCA is that EMOCA has a dedicated expression encoder. This prediction is used to condition the detail generator.

**Comment by kjhgfdsaas** [comment]
got it, many thanks

**Comment by radekd91** [comment]
you're welcome. :-)
